AllCops:
  TargetRubyVersion: 3.2
  DefaultFormatter: progress
  SuggestExtensions: true
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 220

Metrics/ModuleLength:
  Max: 250
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 32

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Layout/HashAlignment:
  Enabled: false
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect
