AllCops:
  TargetRubyVersion: 2.6
  DefaultFormatter: progress
  SuggestExtensions:
    rubocop-rake: true
    rubocop-rspec: true
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "exe/**/*"
    - "tmp/**/*"
    - "extensions/**/*"
    - "spec/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 220

Metrics/ModuleLength:
  Max: 250
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 32

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Metrics/HashAlignment:
  Enabled: false
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Style/Documentation:
  Enabled: false
