FROM ruby:2.6-alpine

RUN apk add --update --no-cache \
        build-base \
        curl-dev \
        git \
        nodejs \
        shared-mime-info \
        sqlite-dev \
        tzdata \
        yaml-dev \
        yarn \
        zlib-dev \
        gcompat

RUN mkdir /app /gem
WORKDIR /app

RUN bundle config set force_ruby_platform true
RUN echo 'gem: --no-rdoc --no-ri' >> "$HOME/.gemrc"
RUN gem update --system 3.2.3
RUN gem install bundler -v 2.4.6
RUN gem install rails -v 5.2.3
RUN gem install rspec-rails -v 4.1.1
RUN rails new .

COPY . /gem
RUN bundle add rails_spotlight --path /gem
RUN echo 'gem "rspec-rails"' >> "Gemfile"
RUN bundle install
RUN rails generate rspec:install

COPY fake_spec_res/routes.rb /app/config/
COPY fake_spec_res/dummy_controller.rb /app/app/controllers/
COPY fake_spec_res/dummy /app/app/views/dummy
COPY fake_spec_res/rails_spotlight_spec.rb /app/spec/integration/

CMD ["bin/rake"]
