services:
  rubocop:
    env_file:
     - 'docker-variables.env'
    build: .
    command: bundle exec rubocop
  spec-rails-6.0:
    env_file:
     - 'docker-variables.env'
    build:
      context: .
      dockerfile: Dockerfile-rails-6.0
  spec-rails-6.1:
    env_file:
     - 'docker-variables.env'
    build:
      context: .
      dockerfile: Dockerfile-rails-6.1
  spec-rails-7.1:
    env_file:
     - 'docker-variables.env'
    build:
      context: .
      dockerfile: Dockerfile-rails-7.1
  spec-rails-8.0:
    env_file:
     - 'docker-variables.env'
    build:
      context: .
      dockerfile: Dockerfile-rails-8.0
  spec-rails-8.0.2:
    env_file:
     - 'docker-variables.env'
    build:
      context: .
      dockerfile: Dockerfile-rails-8.0.2
